# Generated by Django 3.2.25 on 2025-03-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoriatelefone_telefone_tipotelefone_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='detalhes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
