apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']
      - job_name: 'django'
        static_configs:
          - targets: ['django:8000']
      - job_name: 'celery'
        static_configs:
          - targets: ['celery-exporter:8888']
      - job_name: 'node'
        static_configs:
          - targets: ['node-exporter:9100']
